---
title: "Marcelo Rodrigues Ribeiro's CV"
author: Marcelo Rodrigues Ribeiro
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r metathis, echo=FALSE, warning=FALSE}
library(metathis)
meta() %>%
  meta_name("github-repo" = "Mar-celo/CV_Marcelo") %>% 
  meta_social(
    title = "Marcelo Rodrigues Ribeiro's CV",
    description = paste(
      "CV made with the packages RMarkdown, pagedown, datadrivencv."
    ),
    url = "https://mar-celo.github.io/CV_Marcelo/index.html",
    #image = "https://beatrizmilz.github.io/resume/img/share-card.png",
    # image_alt = paste(
    #   "Beatriz Milz CV"
    # ),
    og_type = "website",
    og_author = "Marcelo Rodrigues Ribeiro"
    # twitter_card_type = "summary_large_image",
    # twitter_creator = "@beamilz"
  )
```

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "",
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Veja este CV online com links em https://mar-celo.github.io/CV_Marcelo/index.html")
} else {
  cat("[<i class='fas fa-download'></i> Baixe um PDF deste CV](https://github.com/Mar-celo/CV_Marcelo/raw/master/index.pdf)")
}
```

Contato {#contact}
--------------------------------------------------------------------------------

```{r}
CV %>% print_contact_info()
```


Linguagens {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown) and [**datadrivencv**](http://nickstrayer.me/datadrivencv/index.html).

The source code is available [on github.com/Mar-celo/CV_Marcelo](https://github.com/Mar-celo/CV_Marcelo).

Last updated on `r Sys.Date()`.



Main
================================================================================

Marcelo Rodrigues Ribeiro {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro") 
```



Formação acadêmica {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('Formação')
```



<!-- #Research Experience {data-icon=laptop} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('Experiências') -->
<!-- ``` -->



Experiência {data-icon=suitcase}
--------------------------------------------------------------------------------

::: aside
<br>
<br>
<br>
<br>
<br>
<br>
```{r}
CV %<>% print_text_block('industy_experience_aside')
```
:::

```{r}
CV %<>% print_section('industry_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->
<br>
<br>
<br>

Certificados {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r}
CV %<>% print_text_block('teaching_experience_aside')
```
:::

```{r}
CV %<>% print_section('teaching_positions')
```



<!-- Selected Data Science Writing {data-icon=chart-line} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ::: aside -->
<!-- ```{r} -->
<!-- CV %<>% print_text_block('data_science_writing_aside') -->
<!-- ``` -->
<!-- ::: -->

<!-- ```{r} -->
<!-- CV %<>% print_section('data_science_writings') -->
<!-- ``` -->



<!-- Selected Press (About)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('about_me_press') -->
<!-- ``` -->


<!-- <br> -->
<!-- <br> -->


<!-- Selected Press (By)  {data-icon=newspaper} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('by_me_press') -->
<!-- ``` -->



<!-- Selected Publications, Posters, and Talks {data-icon=book} -->
<!-- -------------------------------------------------------------------------------- -->

<!-- ```{r} -->
<!-- CV %<>% print_section('academic_articles') -->
<!-- ``` -->



```{r}
CV %<>% print_links()
```

